name: 'My First github Action'

on: push

jobs: 
  first_job:
    name: 'First Job'
    runs-on: ubuntu-latest
    steps: 
      - name: 'Say Hello World 1'
        shell: bash
        run:  
          echo "Say Hello from Step #1"
        - name: 'Say Hello World 2'
          shell: push
          run:  
            echo "Say Hello from Step #2"